# Generated by Django 5.1.3 on 2024-11-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='confirmpassword',
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(default='noemail@example.com', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='username',
            field=models.CharField(default='default_username', max_length=100),
        ),
    ]
