# Generated by Django 5.1.3 on 2024-11-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_remove_register_confirmpassword_alter_register_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='username',
            field=models.CharField(default='default_username', max_length=100, unique=True),
        ),
    ]
