# Generated by Django 5.1.3 on 2024-12-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0006_cartdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdb',
            name='Price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cartdb',
            name='TotalPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
