# Generated by Django 5.1.3 on 2024-12-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0008_orderdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdb',
            old_name='Name',
            new_name='FirstName',
        ),
        migrations.AddField(
            model_name='orderdb',
            name='LastName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
